import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { SelectItem } from 'primeng/api';
import Swal, { SweetAlertIcon } from 'sweetalert2';
import { UsuarioService } from '../../../../services/usuario.service';
import { Usuario } from '../../../../models/usuario.model';
import { Comite } from '../../../../interfaces/comite';
import { MenuService } from '../../../../layout/app.menu.service';

// Generated by https://quicktype.io


@Component({
    selector: 'app-form-seleccion-comite',
    templateUrl: './form-seleccion-comite.component.html',
    styles: [
    ]
})
export class FormSeleccionComiteComponent implements OnInit {

    public blocked: boolean = false;
    public disabled: boolean = false;

    public usuario!: Usuario;

    public formSelectComite: FormGroup = this.fb.group({
        id_comite: ['', [Validators.required]]
    });

    public comite: Comite[] = [];
    @Output() cierraModal = new EventEmitter<boolean>();


    constructor(private fb: FormBuilder,
        private usuarioService: UsuarioService, private menuService: MenuService) { }

    ngOnInit(): void {
        this.cargarComites();
        this.cargaInfo();
    }

    cargaInfo() {
        this.blocked = true;
        this.usuario = this.usuarioService.usuario;
        // console.log(this.usuario);
        /* const { uuid,
          estado,
          perfil,
          folio, nombres, primer_apellido, segundo_apellido, genero, edad, curp, telefono_casa, telefono_celular, demarcacion_territorial} = this.usuario; */

        const { id_comite } = this.usuario;

        console.log({ id_comite });


        if (id_comite) {
            this.disabled = true;
        }

        //  setTimeout(() => { this.blocked = false }, 500);

        this.formSelectComite.setValue({ id_comite });
        this.blocked = false;

    }

    cargarComites() {
        this.usuarioService.obtenerComitesActivos()
            .subscribe((resp: any) => {
                console.log(resp);

                const { id_comite } = this.usuario;

                if (id_comite) {
                    this.disabled = true;
                    this.comite = resp.getComitesActivosDB;
                } else {
                    const comitesDB = resp.getComitesActivosDB;

                    let sinLugares = 0;
                    let comitesCount = comitesDB.length;

                    comitesDB.forEach((comite: any) => {
                        console.log(comite);
                        if (comite.lugares_disponibles <= 0) {
                            comite.disabled = true;
                            sinLugares++;
                        }

                        this.comite.push(comite);

                    });

                    if (sinLugares === comitesCount) {
                        Swal.fire({
                            text: 'Lo sentimos, todos los Comités se encuentran completos. En caso de que alguna persona decline su participación, se te hará saber mediante correo electrónico.',
                            icon: 'warning',
                            allowEscapeKey: false,
                            allowOutsideClick: false,
                            confirmButtonText: 'Ok',

                        }).then((result) => {
                            if (result.isConfirmed) {
                                this.menuService.logOut();
                            }
                        });
                    }
                }



                console.log(this.comite);


            })
    }

    guardarEleccionComite() {
        // console.log(this.formSelectComite.value);

        // console.log(id_comite);

        const data = this.formSelectComite.value;
        this.usuarioService.guardarInscripcionComite(data)
            .subscribe((resp: any) => {
                console.log(resp);
                //  (resp.disponible) ? tipoIcon = 'success' : tipoIcon = 'error';
                Swal.fire({ text: resp.msg, icon: 'success', allowEscapeKey: false, allowOutsideClick: false });
                this.cierraModal.emit(true);

            }, (err) => {
                console.log(err);
                // const {  }
                let msg_new = 'Ocurrió un error';
                let title = 'Error';
                let icon: SweetAlertIcon = 'error';
                if (err.error) {
                    icon = 'warning'
                    if (!err.error.con_lugar) {
                        msg_new = err.error.msg;
                        title = 'Lo sentimos';
                    }
                }

                Swal.fire({ title, text: err.error.msg, icon });

            })

    }

    buscarCupoo(id_comite: number) {
        console.log(id_comite);

        if (isNaN(id_comite)) {
            return;
        }

        this.usuarioService.validaCupoInscripcionComite(id_comite)
            .subscribe((resp: any) => {
                console.log(resp);
                const { data } = resp;
                const { cupo, lugares_disponibles, percentDisponible } = data;

                if (lugares_disponibles <= 0) {
                    this.formSelectComite.controls['id_comite'].setValue('');
                    this.formSelectComite.reset();
                }
                let type_icon: SweetAlertIcon = 'success';
                let type_text = 'Con disponibilidad';

                if (percentDisponible < 50 && percentDisponible > 10) {
                    type_icon = 'info';
                    type_text = 'Con disponibilidad menor al 50%';
                } else if (percentDisponible <= 10 && percentDisponible > 0) {
                    type_icon = 'warning';
                    type_text = 'Con disponibilidad menor al 10%';
                } else if (percentDisponible <= 0) {
                    type_icon = 'error';
                    type_text = 'Sin lugares disponibles';
                }

                //  (resp.disponible) ? tipoIcon = 'success' : tipoIcon = 'error';
                Swal.fire({ icon: type_icon, text: type_text, position: 'top-end', showConfirmButton: false, timer: 2000 });

            })

    }

}
