// Generated by https://quicktype.io

export interface ComplementaInformacion {
    telefono_celular:        string;
    telefono_casa:           string;
    demarcacion_territorial: number;
    como_te_enteraste:       number;
}
