export interface ListadoValidacion {
    id_usuario:     number;
    nombres:        string;
    uuid:           string;
    nombre_comite:  string;
    nombre_usuario: string;
}


// Generated by https://quicktype.io

export interface Listado {
    ok:                      boolean;
    usuariosConAsistenciaDB: UsuariosConAsistenciaDB[];
}

export interface UsuariosConAsistenciaDB {
    id_usuario:       number;
    nombres:          string;
    primer_apellido:  string;
    segundo_apellido: string;
    id_comite:        number;
    nombre_comite:    string;
    asistencias:      Asistencia[];
}

export interface Asistencia {
    id_fecha:       number;
    fecha:          string;
    id_usuario:     number;
    nombre_usuario: string;
}
