// Generated by https://quicktype.io

export interface RegistroForm {
    nombres:            string;
    primer_apellido:    string;
    segundo_apellido:   string;
    fecha_nacimiento:   string;
    edad:               string;
    correo_electronico: string;
    contrasena:         string;
    curp:               string;
}
